[versions]
agp = "8.12.2"
kotlin = "2.2.10"
kotlinxCoroutines = "1.10.2"
kotlinxDateTime = "0.7.1"

androidxComposeMaterial3 = "1.3.2"
androidxComposeUi = "1.9.0"
androidxDataStore = "1.1.7"
androidxLifecycle = "2.9.3"
androidxNavigation = "2.9.3"
androidxMedia3 = "1.8.0"
assertk = "0.28.1"
coil = "2.7.0"
dependencyAnalysis = "3.0.1"
desugarJdkLibs = "2.1.5"
detekt = "1.23.8"
downloadPlugin = "5.6.0"

junit = "5.13.4"
junit-platform-launcher = "1.13.4"
kermit = "2.0.8"

mockK = "1.14.5"
vanniktechPlugin = "0.34.0"
versionsPlugin = "0.52.0"

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
download = { id = "de.undercouch.download", version.ref = "downloadPlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
vanniktechPublishing = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechPlugin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin" }

[libraries]
android-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdkLibs" }

assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }

androidx-datastorePrefs = { module = "androidx.datastore:datastore-preferences", version.ref = "androidxDataStore" }
androidx-lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidxLifecycle" }
androidx-navigation-runtime = { module = "androidx.navigation:navigation-runtime", version.ref = "androidxNavigation" }

androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "androidxMedia3" }

coil-base = { module = "io.coil-kt:coil-base", version.ref = "coil" }

compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidxComposeMaterial3" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidxComposeUi" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidxComposeUi" } # Tooling support (Previews, etc.)
compose-material3-windowsize = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "androidxComposeMaterial3" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform-launcher" }

kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlin-time = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDateTime" }

mockK = { module = "io.mockk:mockk", version.ref = "mockK" }
